# Copyright (C) 2024 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

load("@rules_cc//cc:defs.bzl", "cc_binary")
load(":executable_dispatcher_test.bzl", "executable_dispatcher_test")

cc_binary(
    name = "echo",
    srcs = ["echo.c"],
)

executable_dispatcher_test(
    name = "echo_single",
    src = ":echo",
    append_args = ["1"],
)

executable_dispatcher_test(
    name = "echo_space_in_args",
    src = ":echo",
    append_args = ["an argument"],
)

executable_dispatcher_test(
    name = "echo_multiple",
    src = ":echo",
    append_args = [
        "1",
        "hello, world!",
    ],
)

executable_dispatcher_test(
    name = "echo_selected_arg",
    src = ":echo",
    append_args = select({
        "@platforms//cpu:mips64": ["???"],
        "//conditions:default": ["1"],
    }) + ["2"],
)

executable_dispatcher_test(
    name = "in_a_directory/echo",
    src = ":echo",
    append_args = ["1"],
)

executable_dispatcher_test(
    name = "in_a_directory/aliased",
    src = ":echo",
    alias = "in_a/different_directory/alias",
    append_args = ["1"],
)

test_suite(
    name = "executable_dispatcher_test",
    tests = [
        ":echo_multiple",
        ":echo_selected_arg",
        ":echo_single",
        ":echo_space_in_args",
        ":in_a_directory/aliased",
        ":in_a_directory/echo",
    ],
)
